# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12E3t2G3wpVZ7skTO2i3cFJ4P4VYie0v3
"""

# Python Program to Print Positive Numbers in a List

NumList = []
Number = int(input("Please enter the Total Number of List Elements: "))5


for i in range(1, Number + 1):
       value = int(input(" Input%d  : " %i))
    
       NumList.append(value)

print("\nOutput : ")
for j in range(Number):
    if(NumList[j] >= 0):
        print(NumList[j], end = '   ')