# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12E35R8T55V5JyV0ndfhrSZl9p-JC4Cd8
"""

w = input('Please enter a string')
def most_frequent(s):
    d = {}
    for k in s:
         key = k.lower() 
         if key not in d:
            d[key] = 1
         else:
            d[key] += 1
    return d
def sortDict(d):
    lis = list(d.items())
    for i in range(len(lis)):
        for j in range(i,len(lis)-1):
            if lis[j][1] < lis[j+1][1]:
                lis[j],lis[j+1] = lis[j+1],lis[j]
    return lis
res = sortDict(most_frequent(w))
for i in res:
    print(i[0] + ' = ' + str(i[1]))